### PR TITLE
Most subject

### PR DESCRIPTION
**Pull request by TylorS**
This is just for safe-keeping right now.
I have not published most-subject to npm, and don't plan to until it's decided it's the best solution for *most*. If/when that time comes it will need to be added to the *dependencies*

### CODE REVIEW

**Comment by Frikki** [comment]
@TylorS Do you want this reviewed and merged?

When you need a code review, then assign a core contributor to the PR.

**Comment by TylorS** [comment]
I would like to review and merge this once there is a Subject implementation for *most on npm.

**Comment by Frikki** [comment]
Then assign a person, when ready.

**Comment by Frikki** [comment]
Do we still want to merge this, or is it obsolete now with its own repo?

**Pull request merged**
